feat: add github actions pipeline

diff --git a/fosslight-scanner/.github/workflows/ci-cd.yaml b/fosslight-scanner/.github/workflows/ci-cd.yaml
--- a/fosslight-scanner/.github/workflows/ci-cd.yaml
+++ b/fosslight-scanner/.github/workflows/ci-cd.yaml
@@ -2,45 +2,46 @@ name: CI/CD for FOSSLight Scanner VSCode Extension
 
 on:
   push:
-     branches:
+    branches:
       - main
+      - develop
     tags:
-      - 'v*.*.*' 
+      - "v*.*.*"
 
 jobs:
   build-and-publish:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout the code
-      uses: actions/checkout@v2
+      - name: Checkout the code
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: '14'
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: "14"
 
-    - name: Install dependencies
-      run: npm install
+      - name: Install dependencies
+        run: npm install
 
-    - name: Lint and Test
-      run: |
-        npm run lint
-        npm test
+      - name: Lint and Test
+        run: |
+          npm run lint
+          npm test
 
-    - name: Package Extension
-      run: |
-        npm install -g vsce
-        vsce package
+      - name: Package Extension
+        run: |
+          npm install -g vsce
+          vsce package
 
-    - name: Verify LICENSE
-      run: |
-        if [ ! -f LICENSE ]; then
-          echo "LICENSE file not found!"
-          exit 1
-        fi
+      - name: Verify LICENSE
+        run: |
+          if [ ! -f LICENSE ]; then
+            echo "LICENSE file not found!"
+            exit 1
+          fi
 
-    - name: Publish Extension
-      env:
-        VSCE_PAT: ${{ secrets.VSCE_PAT }}
-      run: vsce publish
+      - name: Publish Extension
+        env:
+          VSCE_PAT: ${{ secrets.VSCE_PAT }}
+        run: vsce publish
